routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();


Route::resource('change-password', 'ChangePasswordController', ['only' => ['edit', 'update'], 'parameters' => ['change-password' => 'user']]);

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['permissions.overseer']], function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/home/descargar/{name}', 'HomeController@descargar')->name('home.descargar');
        Route::get('/finanza/index','FinanzasController@index')->name('finanza.index');
        Route::post('/finanza/cargar','FinanzasController@cargar')->name('finanza.cargar');

        Route::resource('/tipodocumento','TipoDocumento\TipoDocumentoController');
        Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
            Route::impersonate();
            Route::resource('users', 'UsersController', ['except' => ['show']]);
            Route::resource('permissions', 'PermissionsController', ['except' => ['show', 'create', 'destroy']]);
            Route::resource('roles', 'RolesController');
            Route::get('/logs', 'ActivitiesController@index')->name('logs.index');
            Route::get('/logs/{model}/{id}/{yourself?}', 'ActivitiesController@show')->name('logs.show');
            Route::resource('notifications', 'NotificationsController', ['only' => ['index', 'update']]);
            Route::resource('unread-notifications', 'UnreadNotificationsController', ['only' => ['index', 'update']]);
        });
    });
});

app/Role.php
<?php

namespace App;

use App\User;
use App\Permission;
use App\Traits\CacheTrait;
use Illuminate\Database\Eloquent\Model;
use App\Traits\RecordsActivity;

class Role extends Model
{
    use CacheTrait, RecordsActivity;

    protected $fillable = ['name', 'description'];

    // Eager loading
    protected $with = ['permissions'];

    // Relationships
    public function users()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class)->withTimestamps();
        ;
    }

    // Relationship methods
    public function assignPermission($permissionId = null)
    {
        $permissions = $this->getCacheRelationship('permissions', true)->pluck('id');
        if (!$permissions->contains($permissionId)) {
            $this->flushCache();

            return $this->permissions()->attach($permissionId);
        }
        return false;
    }

    public function revokePermission($permissionId = null)
    {
        if (!empty($permissionId)) {
            $this->flushCache();

            return $this->permissions()->detach($permissionId);
        }
    }

    public function syncPermissions($permissionIds = null)
    {
        if (!empty($permissionId)) {
            $this->flushCache();

            return $this->permissions()->sync($permissionIds, false);
        }
    }

    public function revokeAllPermissions()
    {
        $this->flushCache();

        return $this->permissions()->detach();
    }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Permission;

class RolesController extends Controller
{
    public function index()
    {
        $roles = Role::orderBy('id', 'ASC')->paginate(10);
        if (request()->wantsJson()) {
            return Role::all();
        }
        return view('admin.roles.index', compact('roles'));
    }

    public function create()
    {
        return view('admin.roles.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|max:255|unique:roles',
            'description' => 'required|string|max:255',
            'permissions' => 'required'
        ]);

        $role = new Role;
        $role->fill($validatedData);
        $role->save();
        $role->revokeAllPermissions();
        $role->assignPermission($validatedData['permissions']);

        if (request()->wantsJson()) {
            return response()->json(['created' => true, 'code' => 201], 201);
        }

        return redirect(route('roles.index'))->with(['flash' => 'haz creado correctamente un rol', 'type' => 'success']);
    }

    //NOTICE: No cuenta con visualizacion de rol
    // public function show(Role $role)
    // {
    //     return view('admin.roles.show', compact('role'));
    // }

    public function edit(Role $role)
    {
        return view('admin.roles.edit', compact('role'));
    }

    public function update(Request $request, Role $role)
    {
        $validatedData = $request->validate([
            'name' => 'sometimes|required|string|max:255|unique:roles,name,' . $role->id,
            'description' => 'sometimes|required|string|max:255',
            'permissions' => 'sometimes|required'
        ]);

        $role->fill($validatedData);
        $role->save();
        $role->revokeAllPermissions();
        $role->assignPermission($validatedData['permissions']);
        if (request()->wantsJson()) {
            return response()->json(['updated' => true, 'code' => 202], 202);
        }

        return redirect(route('roles.index'))->with(['flash' => 'haz actualizado correctamente un rol', 'type' => 'success']);
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('title', 'Crear rol')

@section('breadcrumb')
<li>
    <a href="{{ route('roles.index') }}">roles</a>
</li>
<li class="active">
    <strong>crear<strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-offset-3 col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Crear rol <small>todos los capos son requeridos</small></h5>
            </div>
            <div class="ibox-content">
                <form action="{{ route('roles.store') }}" method="POST" class="form-horizontal">
                        {{ csrf_field() }}
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Descripcion</label>
                        <div class="col-sm-8">
                            <input type="description" class="form-control" name="description" value="{{ old('description') }}">
                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('permissions') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Permisos</label>
                        <div class="col-sm-8">
                            <form-select uri="{{ route('permissions.index') }}" name="permissions"></form-select>
                            @if ($errors->has('permissions'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('permissions') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary pull-right">Crear Rol</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('title', 'Editar Rol')

@section('breadcrumb')
<li>
    <a href="{{ route('roles.index') }}">roles</a>
</li>
<li class="active">
    <strong>editar<strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-offset-3 col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Editar rol <small>todos los capos son requeridos</small></h5>
            </div>
            <div class="ibox-content">
                <form action="{{ route('roles.update', $role) }}" method="POST" class="form-horizontal">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" name="name" value="{{ old('name') ?? $role->name }}">
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Descripcion</label>
                        <div class="col-sm-8">
                            <input type="description" class="form-control" name="description" value="{{ old('description') ?? $role->description }}">
                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('permissions') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Permisos</label>
                        <div class="col-sm-8">
                            @php 
                                $data = $role->permissions->map(function($permission) {
                                    return ['label' => $permission->name, 'key' => $permission->id ];
                                })->toJson();
                            @endphp
                            <form-select :data-value="{{ $data }}" uri="{{ route('permissions.index') }}" name="permissions"></permission-select>
                            @if ($errors->has('permissions'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('permissions') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary pull-right">Guardar Cambios</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')

@section('title', 'Roles')

@section('breadcrumb')
<li class="active">
    <strong>roles</strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Lista de roles </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <span class="pull-right"><a class="btn btn-primary" href="{{ route('roles.create') }}">Crear Rol</a></span>                    
                    <table class="table table-striped table-responsive" cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>Acciones</th>
                        </thead>
                        <tbody>
                        @forelse ($roles as $role)
                            <tr>
                                <td>{{ $role->name }}</td>
                                <td>{{ $role->description }}</td>
                                <td>
                                    <a href="{{ route('roles.edit', $role) }}" class="text-warning" title="Editar">
                                        <i class="fa fa-pencil-square-o fa-2x"></i>
                                    </a>
                                    <a href="{{ route('logs.show', ['role', $role->id, true]) }}"  class="text-primary" title="Log sobre el usuario">
                                        <i class="fa fa-file-text fa-2x"></i>     
                                    </a>
                                </td>
                            </tr>
                        @empty
                            No hay roles
                        @endforelse
                        </tbody>
                    </table>
                    <span class="pull-right">{{ $roles }}</span>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection