routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();


Route::resource('change-password', 'ChangePasswordController', ['only' => ['edit', 'update'], 'parameters' => ['change-password' => 'user']]);

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['permissions.overseer']], function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/home/descargar/{name}', 'HomeController@descargar')->name('home.descargar');
        Route::get('/finanza/index','FinanzasController@index')->name('finanza.index');
        Route::post('/finanza/cargar','FinanzasController@cargar')->name('finanza.cargar');

        Route::resource('/tipodocumento','TipoDocumento\TipoDocumentoController');
        Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
            Route::impersonate();
            Route::resource('users', 'UsersController', ['except' => ['show']]);
            Route::resource('permissions', 'PermissionsController', ['except' => ['show', 'create', 'destroy']]);
            Route::resource('roles', 'RolesController');
            Route::get('/logs', 'ActivitiesController@index')->name('logs.index');
            Route::get('/logs/{model}/{id}/{yourself?}', 'ActivitiesController@show')->name('logs.show');
            Route::resource('notifications', 'NotificationsController', ['only' => ['index', 'update']]);
            Route::resource('unread-notifications', 'UnreadNotificationsController', ['only' => ['index', 'update']]);
        });
    });
});

app/TipoDocumento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TipoDocumento extends Model
{
    protected $table = 'tipos_documentos';

    protected $fillable = [
        'name', 'softland', 'banco_id','estado'
    ];    
}

app/Http/Controllers/TipoDocumento/TipoDocumentoController.php
<?php

namespace App\Http\Controllers\TipoDocumento;

use App\TipoDocumento;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class TipoDocumentoController extends Controller
{
    //
 
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        $tipos = TipoDocumento::orderBy('id', 'ASC')->paginate(20);
        if (request()->wantsJson()) {
            return $tipos;
        }
        return view('tipodocumento.index', compact('tipos'));
    }

    public function create()
    {
        return view('tipodocumento.create');
    }

    protected function store(Request $data)
    {
        $validatedData = $data->validate([
            'name' => 'required|string|max:255',
            'softland' => 'required|string|max:2',
            'banco_id' => 'required|numeric',
            'estado' => 'required'
        ]);
        $docu = new TipoDocumento;
        $docu->fill($validatedData);
        $docu->save();
        return redirect(route('tipodocumento.index'))->with(['flash' => 'haz creado correctamente un evento', 'type' => 'success']);
    }

    public function edit($doc)
    {
        $tipo = TipoDocumento::where('id',$doc)->first();
        return view('tipodocumento.edit', compact('tipo'));
    }

    public function update(Request $request,$doc)
    {
        //$this->authorize('update', $evento);
        $tipo = TipoDocumento::where('id',$doc)->first();
        $validatedData = $request->validate([
            'name' => 'sometimes|required|string|max:255',
            'softland' => 'sometimes|required|string|max:2',
            'banco_id' => 'sometimes|required|numeric',
            'estado' => 'sometimes|required'
        ]);
        $tipo->fill($validatedData);
        $tipo->save();
        if (request()->wantsJson()) {
            return response()->json(['updated' => true, 'code' => 202], 202);
        }

        return redirect(route('tipodocumento.index'))->with(['flash' => 'haz actualizado correctamente un evento', 'type' => 'success']);
    }

}

resources/views/tipodocumento/create.blade.php
@extends('layouts.app')

@section('title', 'Crear Tipo Documento')

@section('breadcrumb')
<li>
    <a href="{{ route('tipodocumento.index') }}">tipo documentos</a>
</li>
<li class="active">
    <strong>crear<strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-offset-3 col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Crear tipo documento <small>todos los capos son requeridos</small></h5>
            </div>
            <div class="ibox-content">
                <form action="{{ route('tipodocumento.store') }}" method="POST" class="form-horizontal">
                        {{ csrf_field() }}
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('softland') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Siglas Softland</label>
                        <div class="col-sm-8">
                            <input class="form-control" name="softland" value="{{ old('softland') }}">
                            @if ($errors->has('softland'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('softland') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('banco_id') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Codigo Banco</label>
                        <div class="col-sm-8">
                            <input class="form-control" name="banco_id">
                            @if ($errors->has('banco_id'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('banco_id') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <input name="estado" type="hidden" value="1">
                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary pull-right">Crear Tipo Documento</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tipodocumento/edit.blade.php
@extends('layouts.app')

@section('title', 'Editar Tipo Documento')

@section('breadcrumb')
<li>
    <a href="{{ route('tipodocumento.index') }}">tipo documentos</a>
</li>
<li class="active">
    <strong>editar</strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-offset-3 col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Creando Tipo Documento <small>todos los capos son requeridos</small></h5>
            </div>
            <div class="ibox-content">
                <form action="{{ route('tipodocumento.update', $tipo) }}" method="POST" class="form-horizontal" role="form">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" name="name" value="{{ old('name') ?? $tipo->name }}">
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('softland') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Sigla Softland</label>
                        <div class="col-sm-8">
                            <input class="form-control" name="softland" value="{{ old('softland') ?? $tipo->softland }}">
                            @if ($errors->has('softland'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('softland') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('banco_id') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Codigo Banco</label>
                        <div class="col-sm-8">
                            <input class="form-control" name="banco_id" value="{{ old('banco_id') ?? $tipo->banco_id }}">
                            @if ($errors->has('banco_id'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('banco_id') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary pull-right">Guardar cambios</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tipodocumento/index.blade.php
@extends('layouts.app')

@section('title', 'Tipo Documentos')

@section('breadcrumb')
<li class="active">
    <strong>tipo documentos</strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Lista de Tipos de Documentos </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <span class="pull-right"><a class="btn btn-primary" href="{{ route('tipodocumento.create') }}">Crear Tipo de Documento</a></span>                    
                    <table class="table table-striped table-responsive" cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Activo</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        @forelse ($tipos as $tipo)
                            <tr>
                                <td>{{ $tipo->name }}</td>
                                <td>
                                    <div class="switch">
                                        <form action="{{ route('tipodocumento.update', $tipo) }}" method="POST">
                                            {{ method_field('PUT') }} 
                                            {{ csrf_field() }}
                                            <div class="onoffswitch">
                                                <input type='hidden' value='0' name='estado'>
                                                <input 
                                                    name="estado" 
                                                    value="1" 
                                                    type="checkbox" 
                                                    class="onoffswitch-checkbox" 
                                                    id="estado-{{ $tipo->id }}" 
                                                    onChange="this.form.submit()" 
                                                    {{ $tipo->estado ? 'checked': null }} 
                                                >
                                                <label class="onoffswitch-label" for="estado-{{ $tipo->id }}">
                                                    <span class="onoffswitch-inner"></span>
                                                    <span class="onoffswitch-switch"></span>
                                                </label>
                                            </div>
                                        </form>
                                    </div>
                                </td>
                                <td>
                                    <a href="{{ route('tipodocumento.edit', $tipo->id) }}" class="text-warning" title="Editar">
                                        <i class="fa fa-pencil-square-o fa-2x"></i>
                                    </a>
                                    <a href="{{ route('tipodocumento.show', $tipo) }}" class="text-warning" title="Ver">
                                        <i class="fa fa-eye fa-2x"></i>
                                    </a>
                                </td>
                            </tr>
                        @empty
                            No hay Usuario
                        @endforelse
                        </tbody>
                    </table>
                    <span class="pull-right">{{ $tipos }}</span>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection