routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();


Route::resource('change-password', 'ChangePasswordController', ['only' => ['edit', 'update'], 'parameters' => ['change-password' => 'user']]);

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['permissions.overseer']], function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/home/descargar/{name}', 'HomeController@descargar')->name('home.descargar');
        Route::get('/finanza/index','FinanzasController@index')->name('finanza.index');
        Route::post('/finanza/cargar','FinanzasController@cargar')->name('finanza.cargar');

        Route::resource('/tipodocumento','TipoDocumento\TipoDocumentoController');
        Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
            Route::impersonate();
            Route::resource('users', 'UsersController', ['except' => ['show']]);
            Route::resource('permissions', 'PermissionsController', ['except' => ['show', 'create', 'destroy']]);
            Route::resource('roles', 'RolesController');
            Route::get('/logs', 'ActivitiesController@index')->name('logs.index');
            Route::get('/logs/{model}/{id}/{yourself?}', 'ActivitiesController@show')->name('logs.show');
            Route::resource('notifications', 'NotificationsController', ['only' => ['index', 'update']]);
            Route::resource('unread-notifications', 'UnreadNotificationsController', ['only' => ['index', 'update']]);
        });
    });
});

app/User.php
<?php

namespace App;

use App\Traits\OverseerTrait;
use App\Traits\RecordsActivity;
use Illuminate\Support\Facades\Auth;
use Illuminate\Notifications\Notifiable;
use Lab404\Impersonate\Models\Impersonate;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, OverseerTrait, RecordsActivity, Impersonate, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Get the activity timeline for the user.
     *
     * @return mixed
     */
    public function activity()
    {
        return $this->hasMany('App\Activity')
            ->with(['user', 'activitable'])
            ->latest();
    }

    public function canImpersonate()
    {
        return $this->isAdmin();
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $users = User::orderBy('id', 'ASC')->paginate(10);
        if (request()->wantsJson()) {
            return $users;
        }
        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
            'active' => 'nullable|min:0|max:1',
            'roles' => 'required'
        ]);

        $user = new User;
        $validatedData['password'] = bcrypt($validatedData['password']);
        $user->fill($validatedData);
        $user->save();
        $user->revokeAllRoles();
        $user->assignRole($validatedData['roles']);

        if (request()->wantsJson()) {
            return response()->json(['created' => true, 'code' => 201], 201);
        }

        return redirect(route('users.index'))->with(['flash' => 'haz creado correctamente un usuario', 'type' => 'success']);
    }

    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    public function update(Request $request, User $user)
    {
        $this->authorize('update', $user);
        $validatedData = $request->validate([
            'name' => 'sometimes|required|string|max:255',
            'email' => 'sometimes|required|string|email|max:255|unique:users,email,' . $user->id,
            'active' => 'sometimes|required|boolean',
            'roles' => 'sometimes'
        ]);

        $user->fill($validatedData);
        $user->save();
        $user->revokeAllRoles();
        $user->assignRole($validatedData['roles']);
        if (request()->wantsJson()) {
            return response()->json(['updated' => true, 'code' => 202], 202);
        }

        return redirect(route('users.index'))->with(['flash' => 'haz actualizado correctamente un usuario', 'type' => 'success']);
    }

    public function destroy(User $user)
    {
        $this->authorize('delete', $user);

        $user->delete();
        if (request()->wantsJson()) {
            return response()->json(['deleted' => true, 'code' => 202], 202);
        }
        return redirect(route('users.index'))->with(['flash' => 'haz eliminado correctamente un usuario', 'type' => 'error']);
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('title', 'Crear usuario')

@section('breadcrumb')
<li>
    <a href="{{ route('users.index') }}">usuarios</a>
</li>
<li class="active">
    <strong>crear<strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-offset-3 col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Crear usuario <small>todos los capos son requeridos</small></h5>
            </div>
            <div class="ibox-content">
                <form action="{{ route('users.store') }}" method="POST" class="form-horizontal">
                        {{ csrf_field() }}
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Email</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" name="email" value="{{ old('email') }}">
                            @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Contraseña</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" name="password">
                            @if ($errors->has('password'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Confirmar contraseña</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" name="password_confirmation">
                            @if ($errors->has('password_confirmation'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password_confirmation') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('active') ? ' has-error' : '' }}"><label class="col-sm-3 control-label">Activo</label>
                        <div class="col-sm-8">
                            <div class="onoffswitch">
                                <input type='hidden' value='0' name='active'>
                                <input 
                                    name="active" 
                                    value="{{ old('active') ?? 1 }}" 
                                    type="checkbox" 
                                    class="onoffswitch-checkbox" 
                                    id="active" 
                                >
                                <label class="onoffswitch-label" for="active">
                                    <span class="onoffswitch-inner"></span>
                                    <span class="onoffswitch-switch"></span>
                                </label>
                                @if ($errors->has('active'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('active') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Roles</label>
                        <div class="col-sm-8">
                            <form-select uri="{{ route('roles.index') }}" name="roles"></form-select>
                            @if ($errors->has('roles'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('roles') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary pull-right">Crear Usuario</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Editar usuario')

@section('breadcrumb')
<li>
    <a href="{{ route('users.index') }}">usuarios</a>
</li>
<li class="active">
    <strong>editar</strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-offset-3 col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Creando usuario <small>todos los capos son requeridos</small></h5>
            </div>
            <div class="ibox-content">
                <form action="{{ route('users.update', $user) }}" method="POST" class="form-horizontal" role="form">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" name="name" value="{{ old('name') ?? $user->name }}">
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Email</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" name="email" value="{{ old('email') ?? $user->email }}">
                            @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group{{ $errors->has('permissions') ? ' has-error' : '' }}">
                        <label class="col-sm-3 control-label">Permisos</label>
                        <div class="col-sm-8">
                            @php 
                                $data = $user->roles->map(function($role) {
                                    return ['label' => $role->name, 'key' => $role->id ];
                                })->toJson();
                            @endphp
                            <form-select :data-value="{{ $data }}" uri="{{ route('roles.index') }}" name="roles"></permission-select>
                            @if ($errors->has('permissions'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('permissions') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary pull-right">Guardar cambios</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('title', 'Usuarios')

@section('breadcrumb')
<li class="active">
    <strong>usuarios</strong>
</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Lista de usuarios </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <span class="pull-right"><a class="btn btn-primary" href="{{ route('users.create') }}">Crear Usuario</a></span>                    
                    <table class="table table-striped table-responsive" cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Email</th>
                                <th>Activo</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        @forelse ($users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    <div class="switch">
                                        <form action="{{ route('users.update', $user) }}" method="POST">
                                            {{ method_field('PUT') }} 
                                            {{ csrf_field() }}
                                            <div class="onoffswitch">
                                                <input type='hidden' value='0' name='active'>
                                                <input 
                                                    name="active" 
                                                    value="1" 
                                                    type="checkbox" 
                                                    class="onoffswitch-checkbox" 
                                                    id="active-{{ $user->id }}" 
                                                    onChange="this.form.submit()" 
                                                    {{ $user->active ? 'checked': null }} 
                                                    {{ $user->isAdmin() ? 'disabled': null }}
                                                >
                                                <label class="onoffswitch-label" for="active-{{ $user->id }}">
                                                    <span class="onoffswitch-inner"></span>
                                                    <span class="onoffswitch-switch"></span>
                                                </label>
                                            </div>
                                        </form>
                                    </div>
                                </td>
                                <td>
                                    <a href="{{ route('users.edit', $user) }}" class="text-warning" title="Editar">
                                        <i class="fa fa-pencil-square-o fa-2x"></i>
                                    </a>
                                    @can('delete', $user)
                                        <form id="delete-user-{{ $user->id }}" action="{{ route('users.destroy', $user) }}" method="POST" style="display: none;" onSubmit="return window.confirm(Estas seguro?);">
                                                {{ method_field('DELETE') }} 
                                                {{ csrf_field() }}
                                        </form>
                                        <a href="javascript:void(0);" class=" text-danger" onClick="event.preventDefault(); document.getElementById('delete-user-{{ $user->id }}').submit();"  title="Eliminar">
                                            <i class="fa fa-trash-o fa-2x"></i>
                                        </a>
                                    @endcan
                                    <a href="{{ route('change-password.edit', $user) }}" class="text-success" title="Cambiar contraseña">
                                        <i class="fa fa-key fa-2x"></i>
                                    </a>
                                    <a href="{{ route('logs.show', ['user', $user->id]) }}" class="text-muted" title="Log del usuario">
                                        <i class="fa fa-file-text-o fa-2x"></i>     
                                    </a>
                                    <a href="{{ route('logs.show', ['user', $user->id, true]) }}"  class="text-primary" title="Log sobre el usuario">
                                        <i class="fa fa-file-text fa-2x"></i>     
                                    </a> 
                                    @can('delete', $user)
                                        @canImpersonate('impersonate', $user)
                                            <a href="{{ route('impersonate', $user->id) }}"  style="color: black;" title="Personificar">
                                                <i class="fa fa-user-secret fa-2x"></i>
                                            </a>
                                        @endCanImpersonate
                                    @endcan
                                </td>
                            </tr>
                        @empty
                            No hay Usuario
                        @endforelse
                        </tbody>
                    </table>
                    <span class="pull-right">{{ $users }}</span>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')
    Users
@endsection