routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();


Route::resource('change-password', 'ChangePasswordController', ['only' => ['edit', 'update'], 'parameters' => ['change-password' => 'user']]);

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['permissions.overseer']], function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/home/descargar/{name}', 'HomeController@descargar')->name('home.descargar');
        Route::get('/finanza/index','FinanzasController@index')->name('finanza.index');
        Route::post('/finanza/cargar','FinanzasController@cargar')->name('finanza.cargar');

        Route::resource('/tipodocumento','TipoDocumento\TipoDocumentoController');
        Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
            Route::impersonate();
            Route::resource('users', 'UsersController', ['except' => ['show']]);
            Route::resource('permissions', 'PermissionsController', ['except' => ['show', 'create', 'destroy']]);
            Route::resource('roles', 'RolesController');
            Route::get('/logs', 'ActivitiesController@index')->name('logs.index');
            Route::get('/logs/{model}/{id}/{yourself?}', 'ActivitiesController@show')->name('logs.show');
            Route::resource('notifications', 'NotificationsController', ['only' => ['index', 'update']]);
            Route::resource('unread-notifications', 'UnreadNotificationsController', ['only' => ['index', 'update']]);
        });
    });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IRFE - @yield('title') </title>
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="stylesheet" href="{!! asset('css/vendor.css') !!}" />
    <link rel="stylesheet" href="{!! asset('css/app.css') !!}" />

</head>
<body class="fixed-sidebar">

  <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @include('layouts.navigation')

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            @include('layouts.topnavbar')

            <!-- Breadcrumb view -->
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-8">
                    <h2>@yield('title')</h2>
                    <ol class="breadcrumb">
                        <li class="active">
                            <a href="{{ route('home') }}">Inicio</a>
                        </li>
                        @yield('breadcrumb')
                    </ol>
                </div>
            </div>
            <div class="wrapper wrapper-content" style="font-weight: normal; font-size: 12px;">
                <!-- Main view  -->
                @yield('content')
                <flash title="{{ Auth::user()->name }}:" message="{{ session('flash') }}" level="{{ session('type') }}"></flash>

            </div>

            <!-- Footer -->
            @include('layouts.footer')

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

<script src="{!! asset('js/app.js') !!}" type="text/javascript"></script>
<script src="{!! asset('js/main.js') !!}" type="text/javascript"></script>

@section('scripts')
@show

</body>
</html>

resources/views/layouts/footer.blade.php
<div class="footer">
    <div class="pull-right">
        
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2020-2022
    </div>
</div>

resources/views/layouts/navigation.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
	<div class="sidebar-collapse">
		<ul class="nav metismenu" id="side-menu">
			<li class="nav-header">
				<div class="dropdown profile-element">
					<span>
                        <img src="{{ asset('files/irfe.png')}}" width="55" alt="" class="img-circle">
                    </span>
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">{{ Auth::user()->name }}</strong>
                            </span> <span class="text-muted text-xs block">Finanzas<b class="caret"></b></span>
                        </span>
                    </a>
					<ul class="dropdown-menu animated fadeInRight m-t-xs">
						<li>
							<a href="#">
                                    <i class="fa fa-user"></i> Perfil
                            </a>
						</li>
						<li>
							<a href="#">
                                <i class="fa fa-envelope"></i> Mensajes
                            </a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form-2').submit();">
                                <i class="fa fa-sign-out"></i> Salir
                            </a>
							<form id="logout-form-2" action="{{ route('logout') }}" method="POST" style="display: none;">
								{{ csrf_field() }}
							</form>
						</li>
						@impersonating
						<li>
							<a href="{{ route('impersonate.leave') }}">
								<i class="fa fa-user-secret"></i><i class="fa fa-sign-out"></i> Dejar de personificar
							</a>
						</li>
						@endImpersonating
					</ul>
				</div>
				<div class="logo-element">
					HT+
				</div>
			</li>
			<li class="{{ isActiveRoute('home') }}">
				<a href="{{ route('home') }}"><i class="fa fa-th-large"></i> <span class="nav-label">Inicio</span></a>
			</li>
            <li class="{{ isActiveRoute('resources') }}">
                <a href="javascript:void(0);"><i class="fa fa-users"></i><span class="nav-label">Finanzas</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse" style="height: 0px;">
                    <li class="isActiveRoute('home')"><a href="{{ route('finanza.index') }}"><i class="fa fa-search"></i>Conciliacion</a></li>
                    <!--<li class="isActiveRoute('home')"><a href="{{ route('roles.index') }}"><i class="fa fa-user-plus"></i>Agregar</a></li>-->
                </ul>
            </li> 
<!--            <li class="{{ isActiveRoute('offer') }}">
                <a href="javascript:void(0);"><i class="fa fa-handshake-o"></i><span class="nav-label">Ofertas Laborales</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse" style="height: 0px;">
                    <li class="isActiveRoute('home')"><a href="{{ route('roles.index') }}"><i class="fa fa-search"></i>Buscar</a></li>
                    <li class="isActiveRoute('home')"><a href="{{ route('roles.index') }}"><i class="fa fa-user-plus"></i>Agregar</a></li>
                    <li class="isActiveRoute('home')"><a href="{{ route('roles.index') }}"><i class="fa fa-list"></i>Listar</a></li>
                </ul>
            </li> 
            <li class="{{ isActiveRoute('maintainers') }}">
                <a href="javascript:void(0);"><i class="fa fa-gears"></i><span class="nav-label">Mantenedores</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse" style="height: 0px;">
                    <li class="isActiveRoute('home')"><a href="{{ route('roles.index') }}">Competencias</a></li>
                    <li class="isActiveRoute('home')"><a href="{{ route('roles.index') }}">Carreras</a></li>
                    <li class="isActiveRoute('home')"><a href="{{ route('roles.index') }}">Categorias</a></li>
                </ul>
            </li> -->
			<li class="{{ isActiveRoute('roles') }} {{ isActiveRoute('permissions') }} {{ isActiveRoute('users') }} {{ isActiveRoute('logs') }}">
				<a href="javascript:void(0);"><i class="fa fa-laptop"></i><span class="nav-label">Administración</span> <span class="fa arrow"></span></a>
				<ul class="nav nav-second-level collapse" style="height: 0px;">
					@if(auth()->user()->hasRole('Admin'))
                    <li class="{{ isActiveRoute('users') }}"><a href="{{ route('users.index') }}" id="damian"><i class="fa fa-users"></i>Usuarios</a></li>
					<li class="{{ isActiveRoute('roles') }}"><a href="{{ route('roles.index') }}"><i class="fa fa-address-card"></i>Roles</a></li>
					<li class="{{ isActiveRoute('permissions') }}"><a href="{{ route('permissions.index') }}"><i class="fa fa-user-secret"></i>Permisos</a></li>
                    <li class="{{ isActiveRoute('logs') }}"><a href="{{ route('logs.index') }}"><i class="fa fa-file-text"></i>Logs</a></li>
                    @endif
                    <li class="{{ isActiveRoute('logs') }}"><a href="{{ route('tipodocumento.index') }}"><i class="fa fa-file-text"></i>Tipos Documentos</a></li>
				</ul>
            </li>               
		</ul>
	</div>
</nav>

resources/views/layouts/public.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>IRFE - @yield('title') </title>
    <link rel="stylesheet" href="{!! asset('css/vendor.css') !!}" />
    <link rel="stylesheet" href="{!! asset('css/app.css') !!}" />
</head>
<body class="gray-bg">
    <div class="middle-box text-center loginscreen animated fadeInDown" id="app">
        <div id="wrapper">
            @yield('content')
        </div>
    </div>    
    <script src="{!! asset('js/app.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('js/main.js') !!}" type="text/javascript"></script>
</body>
</html>

resources/views/layouts/topnavbar.blade.php
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="/">
                <div class="form-group">
                    <input type="text" placeholder="" class="form-control" name="top-search" id="top-search" />
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <!--<li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#" aria-expanded="false">
                    <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="https://scontent.fscl14-1.fna.fbcdn.net/v/t1.0-1/p80x80/17353312_10211368131493981_4314191449503901504_n.jpg?oh=829362e45b722e771e7a7200c9191a5e&oe=5AC839A5">
                            </a>
                            <div class="media-body">
                                <small class="pull-right">46h ago</small>
                                <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="https://scontent.fscl14-1.fna.fbcdn.net/v/t1.0-1/p80x80/17353312_10211368131493981_4314191449503901504_n.jpg?oh=829362e45b722e771e7a7200c9191a5e&oe=5AC839A5">
                            </a>
                            <div class="media-body">
                                <small class="pull-right text-navy">5h ago</small>
                                <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="https://scontent.fscl14-1.fna.fbcdn.net/v/t1.0-1/p80x80/17353312_10211368131493981_4314191449503901504_n.jpg?oh=829362e45b722e771e7a7200c9191a5e&oe=5AC839A5">
                            </a>
                            <div class="media-body ">
                                <small class="pull-right">23h ago</small>
                                <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="mailbox.html">
                                <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>-->
            <my-notifications></my-notifications>
            <li>
                <a href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                    <i class="fa fa-sign-out"></i>Salir
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </li>
        </ul>
    </nav>
</div>